### ISSUE TITLE
Usage Issues with latest nuget packages (0.3.0-0.3.2)

### ISSUE THREAD

**Issue by ExtremeSwat** [Dutchskull/Aspire.PolyRepo#18]
Heya, I've been trying to use the latest package (0.3.2)

I've created a starter ASPIRE.NET orchestrator project, added the nugetPackge (0.3.2) and whenever I try to use any extension method such as `AddRepository` I encounter issues (... does not contain definition)

Tried to manually add the using with no avail.

**Comment by WhiteOlivierus** [comment]
Thank you for the notice, could you share a demo repo. We have been using this and haven't had this problem yet.

**Comment by WhiteOlivierus** [comment]
@ExtremeSwat did you have any update, otherwise I will close this issue

**Comment by danjaniell** [comment]
@WhiteOlivierus Same with me. Can't add using statement as it can't find Dutchskull.Aspire.PolyRepo.

**Comment by WhiteOlivierus** [comment]
Has been fixed, there were differences between internal repo and public
