### ISSUE TITLE
Git Worktrees Support

### ISSUE THREAD

**Issue by slang25** [Dutchskull/Aspire.PolyRepo#20]
Hey, this project is really nice, I was wishing for something like this to come along, and this was better than I had hoped for.

It would be great if there was also an option to use git worktrees (great explanation [here](https://www.gitkraken.com/learn/git/git-worktree)), which is a feature that is support by [libgit2sharp](https://github.com/libgit2/libgit2sharp/blob/5085a0c6173cdb2a3fde205330b327a8eb0a26c4/LibGit2Sharp.Tests/WorktreeFixture.cs#L250).

I was thinking it would be optional, but would allow for essentially creating addition checked-out version of repositories where they may already be cloned (and have pending changes) which would make my day-to-day workflow more practical.

**Comment by WhiteOlivierus** [comment]
Thank you for the suggestion. I am not familiar with this workflow, so I would have to dive into this. But if you have a suggestion on how to implement it, you could open a pr.

**Comment by slang25** [comment]
@WhiteOlivierus thanks, I haven't got any ideas yet, but it's on my list of things to look at when I get a spare evening. I'll have a go at implementing what I had in mind, but that's when I often find out that my great ideas aren't that great 😅

**Comment by WhiteOlivierus** [comment]
Any luck on seeing if this would be a feature that is handy?

**Comment by WhiteOlivierus** [comment]
Just checking in on the progress. If there have been any hurdles encountered, please document them here so we can address the issues effectively. Thank you!

**Comment by WhiteOlivierus** [comment]
I'm closing this issue, because there has not been a reaction for a while.
