### ISSUE TITLE
Aspire community toolkit & Aspire 9

### ISSUE THREAD

**Issue by FullStackChef** [Dutchskull/Aspire.PolyRepo#51]
Hi - Just wondering if you're considering migrating this to the community toolkit and or updating to aspire 9

**Comment by WhiteOlivierus** [comment]
Thank you for your interest! I've considered submitting this repository to the Community Toolkit, but there are a few features I still want to develop and refine before making that move. Unfortunately, my availability to work on this project is currently limited, so it may take some time.

As for compatibility with .NET Aspire 9, the project should already be fully compatible. Let me know if you encounter any issues or have further questions!
