### ISSUE TITLE
Repo Credential support?

### ISSUE THREAD

**Issue by PaybackMan** [Dutchskull/Aspire.PolyRepo#52]
Is there a way to supply repo credentials? I'm using Devops...

**Comment by PaybackMan** [comment]
May have found it

IResourceBuilder<RepositoryResource> repository = builder.AddRepository(
    "repository",
    "https://github.com/Dutchskull/Aspire-Git.git",
    c => c
        .WithDefaultBranch("develop")
        .KeepUpToDate()
        .WithGitConfig(builder => builder.WithAuthentication("", ""))
        .WithTargetPath("../../repos"));

**Comment by WhiteOlivierus** [comment]
That is correct, I thought I updated the documentation, will be doing this shortly.
